// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef EMPLOYEE_ODB_HXX
#define EMPLOYEE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "employee.hxx"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/tr1/wrapper-traits.hxx>
#include <odb/tr1/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/view-image.hxx>
#include <odb/view-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // country
  //
  template <>
  struct class_traits< ::country >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::country >
  {
    public:
    typedef ::country object_type;
    typedef ::std::tr1::shared_ptr< ::country > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // employer
  //
  template <>
  struct class_traits< ::employer >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::employer >
  {
    public:
    typedef ::employer object_type;
    typedef ::std::tr1::shared_ptr< ::employer > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // employee
  //
  template <>
  struct class_traits< ::employee >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::employee >
  {
    public:
    typedef ::employee object_type;
    typedef ::std::tr1::shared_ptr< ::employee > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // employee_name
  //
  template <>
  struct class_traits< ::employee_name >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_name >
  {
    public:
    typedef ::employee_name view_type;
    typedef ::std::tr1::shared_ptr< ::employee_name > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employee_count
  //
  template <>
  struct class_traits< ::employee_count >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_count >
  {
    public:
    typedef ::employee_count view_type;
    typedef ::std::tr1::shared_ptr< ::employee_count > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employee_employer
  //
  template <>
  struct class_traits< ::employee_employer >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_employer >
  {
    public:
    typedef ::employee_employer view_type;
    typedef ::std::tr1::shared_ptr< ::employee_employer > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employer_age
  //
  template <>
  struct class_traits< ::employer_age >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employer_age >
  {
    public:
    typedef ::employer_age view_type;
    typedef ::std::tr1::shared_ptr< ::employer_age > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employee_country
  //
  template <>
  struct class_traits< ::employee_country >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_country >
  {
    public:
    typedef ::employee_country view_type;
    typedef ::std::tr1::shared_ptr< ::employee_country > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employee_country_objects
  //
  template <>
  struct class_traits< ::employee_country_objects >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_country_objects >
  {
    public:
    typedef ::employee_country_objects view_type;
    typedef ::std::tr1::shared_ptr< ::employee_country_objects > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employer_with_employees
  //
  template <>
  struct class_traits< ::employer_with_employees >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employer_with_employees >
  {
    public:
    typedef ::employer_with_employees view_type;
    typedef ::std::tr1::shared_ptr< ::employer_with_employees > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employee_vacation
  //
  template <>
  struct class_traits< ::employee_vacation >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_vacation >
  {
    public:
    typedef ::employee_vacation view_type;
    typedef ::std::tr1::shared_ptr< ::employee_vacation > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employee_vacation1
  //
  template <>
  struct class_traits< ::employee_vacation1 >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_vacation1 >
  {
    public:
    typedef ::employee_vacation1 view_type;
    typedef ::std::tr1::shared_ptr< ::employee_vacation1 > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employee_vacation2
  //
  template <>
  struct class_traits< ::employee_vacation2 >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_vacation2 >
  {
    public:
    typedef ::employee_vacation2 view_type;
    typedef ::std::tr1::shared_ptr< ::employee_vacation2 > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // employee_prev_employer
  //
  template <>
  struct class_traits< ::employee_prev_employer >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::employee_prev_employer >
  {
    public:
    typedef ::employee_prev_employer view_type;
    typedef ::std::tr1::shared_ptr< ::employee_prev_employer > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // country
  //
  template <typename A>
  struct query_columns< ::country, id_mysql, A >
  {
    // code
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    code_type_;

    static const code_type_ code;

    // name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    name_type_;

    static const name_type_ name;
  };

  template <typename A>
  const typename query_columns< ::country, id_mysql, A >::code_type_
  query_columns< ::country, id_mysql, A >::
  code (A::table_name, "`code`", 0);

  template <typename A>
  const typename query_columns< ::country, id_mysql, A >::name_type_
  query_columns< ::country, id_mysql, A >::
  name (A::table_name, "`name`", 0);

  template <typename A>
  struct pointer_query_columns< ::country, id_mysql, A >:
    query_columns< ::country, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::country, id_mysql >:
    public access::object_traits< ::country >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      unsigned long id_size;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // code_
      //
      details::buffer code_value;
      unsigned long code_size;
      my_bool code_null;

      // name_
      //
      details::buffer name_value;
      unsigned long name_size;
      my_bool name_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::country, id_common >:
    public access::object_traits_impl< ::country, id_mysql >
  {
  };

  // employer
  //
  template <typename A>
  struct query_columns< ::employer, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    name_type_;

    static const name_type_ name;
  };

  template <typename A>
  const typename query_columns< ::employer, id_mysql, A >::id_type_
  query_columns< ::employer, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::employer, id_mysql, A >::name_type_
  query_columns< ::employer, id_mysql, A >::
  name (A::table_name, "`name`", 0);

  template <typename A>
  struct pointer_query_columns< ::employer, id_mysql, A >:
    query_columns< ::employer, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::employer, id_mysql >:
    public access::object_traits< ::employer >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      unsigned long long id_value;
      my_bool id_null;

      // name_
      //
      details::buffer name_value;
      unsigned long name_size;
      my_bool name_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::employer, id_common >:
    public access::object_traits_impl< ::employer, id_mysql >
  {
  };

  // employee
  //
  template <typename A>
  struct pointer_query_columns< ::employee, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // first
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    first_type_;

    static const first_type_ first;

    // last
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    last_type_;

    static const last_type_ last;

    // age
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        short unsigned int,
        mysql::id_ushort >::query_type,
      mysql::id_ushort >
    age_type_;

    static const age_type_ age;

    // residence
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    residence_type_;

    static const residence_type_ residence;

    // nationality
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    nationality_type_;

    static const nationality_type_ nationality;

    // employed_by
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    employed_by_type_;

    static const employed_by_type_ employed_by;
  };

  template <typename A>
  const typename pointer_query_columns< ::employee, id_mysql, A >::id_type_
  pointer_query_columns< ::employee, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::employee, id_mysql, A >::first_type_
  pointer_query_columns< ::employee, id_mysql, A >::
  first (A::table_name, "`first`", 0);

  template <typename A>
  const typename pointer_query_columns< ::employee, id_mysql, A >::last_type_
  pointer_query_columns< ::employee, id_mysql, A >::
  last (A::table_name, "`last`", 0);

  template <typename A>
  const typename pointer_query_columns< ::employee, id_mysql, A >::age_type_
  pointer_query_columns< ::employee, id_mysql, A >::
  age (A::table_name, "`age`", 0);

  template <typename A>
  const typename pointer_query_columns< ::employee, id_mysql, A >::residence_type_
  pointer_query_columns< ::employee, id_mysql, A >::
  residence (A::table_name, "`residence`", 0);

  template <typename A>
  const typename pointer_query_columns< ::employee, id_mysql, A >::nationality_type_
  pointer_query_columns< ::employee, id_mysql, A >::
  nationality (A::table_name, "`nationality`", 0);

  template <typename A>
  const typename pointer_query_columns< ::employee, id_mysql, A >::employed_by_type_
  pointer_query_columns< ::employee, id_mysql, A >::
  employed_by (A::table_name, "`employed_by`", 0);

  template <>
  class access::object_traits_impl< ::employee, id_mysql >:
    public access::object_traits< ::employee >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      unsigned long long id_value;
      my_bool id_null;

      // first_
      //
      details::buffer first_value;
      unsigned long first_size;
      my_bool first_null;

      // last_
      //
      details::buffer last_value;
      unsigned long last_size;
      my_bool last_null;

      // age_
      //
      unsigned short age_value;
      my_bool age_null;

      // residence_
      //
      details::buffer residence_value;
      unsigned long residence_size;
      my_bool residence_null;

      // nationality_
      //
      details::buffer nationality_value;
      unsigned long nationality_size;
      my_bool nationality_null;

      // employed_by_
      //
      unsigned long long employed_by_value;
      my_bool employed_by_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct residence_tag;
    struct nationality_tag;
    struct employed_by_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::employee, id_common >:
    public access::object_traits_impl< ::employee, id_mysql >
  {
  };

  // employee_name
  //
  template <>
  class access::view_traits_impl< ::employee_name, id_mysql >:
    public access::view_traits< ::employee_name >
  {
    public:
    struct image_type
    {
      // first
      //
      details::buffer first_value;
      unsigned long first_size;
      my_bool first_null;

      // last
      //
      details::buffer last_value;
      unsigned long last_size;
      my_bool last_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 2UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_name, id_common >:
    public access::view_traits_impl< ::employee_name, id_mysql >
  {
  };

  // employee_count
  //
  template <>
  class access::view_traits_impl< ::employee_count, id_mysql >:
    public access::view_traits< ::employee_count >
  {
    public:
    struct image_type
    {
      // count
      //
      unsigned long long count_value;
      my_bool count_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 1UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_count, id_common >:
    public access::view_traits_impl< ::employee_count, id_mysql >
  {
  };

  // employee_employer
  //
  template <>
  class access::view_traits_impl< ::employee_employer, id_mysql >:
    public access::view_traits< ::employee_employer >
  {
    public:
    struct image_type
    {
      // first
      //
      details::buffer first_value;
      unsigned long first_size;
      my_bool first_null;

      // last
      //
      details::buffer last_value;
      unsigned long last_size;
      my_bool last_null;

      // employer_name
      //
      details::buffer employer_name_value;
      unsigned long employer_name_size;
      my_bool employer_name_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 3UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_employer, id_common >:
    public access::view_traits_impl< ::employee_employer, id_mysql >
  {
  };

  // employer_age
  //
  template <>
  class access::view_traits_impl< ::employer_age, id_mysql >:
    public access::view_traits< ::employer_age >
  {
    public:
    struct image_type
    {
      // employer_name
      //
      details::buffer employer_name_value;
      unsigned long employer_name_size;
      my_bool employer_name_null;

      // min_age
      //
      unsigned short min_age_value;
      my_bool min_age_null;

      // max_age
      //
      unsigned short max_age_value;
      my_bool max_age_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 3UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employer_age, id_common >:
    public access::view_traits_impl< ::employer_age, id_mysql >
  {
  };

  // employee_country
  //
  template <>
  class access::view_traits_impl< ::employee_country, id_mysql >:
    public access::view_traits< ::employee_country >
  {
    public:
    struct image_type
    {
      // first
      //
      details::buffer first_value;
      unsigned long first_size;
      my_bool first_null;

      // last
      //
      details::buffer last_value;
      unsigned long last_size;
      my_bool last_null;

      // res_country_name
      //
      details::buffer res_country_name_value;
      unsigned long res_country_name_size;
      my_bool res_country_name_null;

      // nat_country_name
      //
      details::buffer nat_country_name_value;
      unsigned long nat_country_name_size;
      my_bool nat_country_name_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    struct res_country_tag;
    struct nat_country_tag;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 4UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_country, id_common >:
    public access::view_traits_impl< ::employee_country, id_mysql >
  {
  };

  // employee_country_objects
  //
  template <>
  class access::view_traits_impl< ::employee_country_objects, id_mysql >:
    public access::view_traits< ::employee_country_objects >
  {
    public:
    struct image_type
    {
      // e
      //
      object_traits_impl< ::employee, id_mysql >::image_type e_value;

      // res
      //
      object_traits_impl< ::country, id_mysql >::image_type res_value;

      // nat
      //
      object_traits_impl< ::country, id_mysql >::image_type nat_value;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    struct res_tag;
    struct nat_tag;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 11UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_country_objects, id_common >:
    public access::view_traits_impl< ::employee_country_objects, id_mysql >
  {
  };

  // employer_with_employees
  //
  template <>
  class access::view_traits_impl< ::employer_with_employees, id_mysql >:
    public access::view_traits< ::employer_with_employees >
  {
    public:
    struct image_type
    {
      // e
      //
      object_traits_impl< ::employer, id_mysql >::image_type e_value;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 2UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employer_with_employees, id_common >:
    public access::view_traits_impl< ::employer_with_employees, id_mysql >
  {
  };

  // employee_vacation
  //
  template <>
  class access::view_traits_impl< ::employee_vacation, id_mysql >:
    public access::view_traits< ::employee_vacation >
  {
    public:
    struct image_type
    {
      // id
      //
      int id_value;
      my_bool id_null;

      // days
      //
      int days_value;
      my_bool days_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns
    {
    };

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 2UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_vacation, id_common >:
    public access::view_traits_impl< ::employee_vacation, id_mysql >
  {
  };

  // employee_vacation1
  //
  template <>
  class access::view_traits_impl< ::employee_vacation1, id_mysql >:
    public access::view_traits< ::employee_vacation1 >
  {
    public:
    struct image_type
    {
      // id
      //
      int id_value;
      my_bool id_null;

      // days
      //
      int days_value;
      my_bool days_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns
    {
    };

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 2UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_vacation1, id_common >:
    public access::view_traits_impl< ::employee_vacation1, id_mysql >
  {
  };

  // employee_vacation2
  //
  template <>
  class access::view_traits_impl< ::employee_vacation2, id_mysql >:
    public access::view_traits< ::employee_vacation2 >
  {
    public:
    struct image_type
    {
      // first
      //
      details::buffer first_value;
      unsigned long first_size;
      my_bool first_null;

      // last
      //
      details::buffer last_value;
      unsigned long last_size;
      my_bool last_null;

      // days
      //
      int days_value;
      my_bool days_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 3UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_vacation2, id_common >:
    public access::view_traits_impl< ::employee_vacation2, id_mysql >
  {
  };

  // employee_prev_employer
  //
  template <>
  class access::view_traits_impl< ::employee_prev_employer, id_mysql >:
    public access::view_traits< ::employee_prev_employer >
  {
    public:
    struct image_type
    {
      // first
      //
      details::buffer first_value;
      unsigned long first_size;
      my_bool first_null;

      // last
      //
      details::buffer last_value;
      unsigned long last_size;
      my_bool last_null;

      // prev_employer_name
      //
      details::buffer prev_employer_name_value;
      unsigned long prev_employer_name_size;
      my_bool prev_employer_name_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 3UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::employee_prev_employer, id_common >:
    public access::view_traits_impl< ::employee_prev_employer, id_mysql >
  {
  };

  // country
  //
  // employer
  //
  // employee
  //
  template <>
  struct alias_traits<
    ::country,
    id_mysql,
    access::object_traits_impl< ::employee, id_mysql >::residence_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::country,
    id_mysql,
    access::object_traits_impl< ::employee, id_mysql >::nationality_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::employer,
    id_mysql,
    access::object_traits_impl< ::employee, id_mysql >::employed_by_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::employee, id_mysql >
  {
    // residence
    //
    typedef
    odb::alias_traits<
      ::country,
      id_mysql,
      access::object_traits_impl< ::employee, id_mysql >::residence_tag>
    residence_alias_;

    // nationality
    //
    typedef
    odb::alias_traits<
      ::country,
      id_mysql,
      access::object_traits_impl< ::employee, id_mysql >::nationality_tag>
    nationality_alias_;

    // employed_by
    //
    typedef
    odb::alias_traits<
      ::employer,
      id_mysql,
      access::object_traits_impl< ::employee, id_mysql >::employed_by_tag>
    employed_by_alias_;
  };

  template <typename A>
  struct query_columns< ::employee, id_mysql, A >:
    query_columns_base< ::employee, id_mysql >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // first
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    first_type_;

    static const first_type_ first;

    // last
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    last_type_;

    static const last_type_ last;

    // age
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        short unsigned int,
        mysql::id_ushort >::query_type,
      mysql::id_ushort >
    age_type_;

    static const age_type_ age;

    // residence
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    residence_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::country,
        id_mysql,
        residence_alias_ > >
    residence_pointer_type_;

    struct residence_type_: residence_pointer_type_, residence_column_type_
    {
      residence_type_ (const char* t, const char* c, const char* conv)
        : residence_column_type_ (t, c, conv)
      {
      }
    };

    static const residence_type_ residence;

    // nationality
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    nationality_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::country,
        id_mysql,
        nationality_alias_ > >
    nationality_pointer_type_;

    struct nationality_type_: nationality_pointer_type_, nationality_column_type_
    {
      nationality_type_ (const char* t, const char* c, const char* conv)
        : nationality_column_type_ (t, c, conv)
      {
      }
    };

    static const nationality_type_ nationality;

    // employed_by
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    employed_by_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::employer,
        id_mysql,
        employed_by_alias_ > >
    employed_by_pointer_type_;

    struct employed_by_type_: employed_by_pointer_type_, employed_by_column_type_
    {
      employed_by_type_ (const char* t, const char* c, const char* conv)
        : employed_by_column_type_ (t, c, conv)
      {
      }
    };

    static const employed_by_type_ employed_by;
  };

  template <typename A>
  const typename query_columns< ::employee, id_mysql, A >::id_type_
  query_columns< ::employee, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::employee, id_mysql, A >::first_type_
  query_columns< ::employee, id_mysql, A >::
  first (A::table_name, "`first`", 0);

  template <typename A>
  const typename query_columns< ::employee, id_mysql, A >::last_type_
  query_columns< ::employee, id_mysql, A >::
  last (A::table_name, "`last`", 0);

  template <typename A>
  const typename query_columns< ::employee, id_mysql, A >::age_type_
  query_columns< ::employee, id_mysql, A >::
  age (A::table_name, "`age`", 0);

  template <typename A>
  const typename query_columns< ::employee, id_mysql, A >::residence_type_
  query_columns< ::employee, id_mysql, A >::
  residence (A::table_name, "`residence`", 0);

  template <typename A>
  const typename query_columns< ::employee, id_mysql, A >::nationality_type_
  query_columns< ::employee, id_mysql, A >::
  nationality (A::table_name, "`nationality`", 0);

  template <typename A>
  const typename query_columns< ::employee, id_mysql, A >::employed_by_type_
  query_columns< ::employee, id_mysql, A >::
  employed_by (A::table_name, "`employed_by`", 0);

  // employee_name
  //
  struct access::view_traits_impl< ::employee_name, id_mysql >::query_columns:
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
  {
  };

  // employee_count
  //
  struct access::view_traits_impl< ::employee_count, id_mysql >::query_columns:
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
  {
  };

  // employee_employer
  //
  struct access::view_traits_impl< ::employee_employer, id_mysql >::query_columns
  {
    // employee
    //
    typedef
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
    employee;

    // employer
    //
    typedef
    odb::pointer_query_columns<
      ::employer,
      id_mysql,
      odb::access::object_traits_impl< ::employer, id_mysql > >
    employer;
  };

  // employer_age
  //
  struct access::view_traits_impl< ::employer_age, id_mysql >::query_columns
  {
    // employee
    //
    typedef
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
    employee;

    // employer
    //
    typedef
    odb::pointer_query_columns<
      ::employer,
      id_mysql,
      odb::access::object_traits_impl< ::employer, id_mysql > >
    employer;
  };

  // employee_country
  //
  template <>
  struct alias_traits<
    ::country,
    id_mysql,
    access::view_traits_impl< ::employee_country, id_mysql >::res_country_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::country,
    id_mysql,
    access::view_traits_impl< ::employee_country, id_mysql >::nat_country_tag>
  {
    static const char table_name[];
  };

  struct access::view_traits_impl< ::employee_country, id_mysql >::query_columns
  {
    // employee
    //
    typedef
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
    employee;

    // res_country
    //
    typedef
    odb::pointer_query_columns<
      ::country,
      id_mysql,
      odb::alias_traits< ::country,
        id_mysql,
        access::view_traits_impl< ::employee_country, id_mysql >::res_country_tag> >
    res_country;

    // nat_country
    //
    typedef
    odb::pointer_query_columns<
      ::country,
      id_mysql,
      odb::alias_traits< ::country,
        id_mysql,
        access::view_traits_impl< ::employee_country, id_mysql >::nat_country_tag> >
    nat_country;
  };

  // employee_country_objects
  //
  template <>
  struct alias_traits<
    ::country,
    id_mysql,
    access::view_traits_impl< ::employee_country_objects, id_mysql >::res_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::country,
    id_mysql,
    access::view_traits_impl< ::employee_country_objects, id_mysql >::nat_tag>
  {
    static const char table_name[];
  };

  struct access::view_traits_impl< ::employee_country_objects, id_mysql >::query_columns
  {
    // employee
    //
    typedef
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
    employee;

    // res
    //
    typedef
    odb::pointer_query_columns<
      ::country,
      id_mysql,
      odb::alias_traits< ::country,
        id_mysql,
        access::view_traits_impl< ::employee_country_objects, id_mysql >::res_tag> >
    res;

    // nat
    //
    typedef
    odb::pointer_query_columns<
      ::country,
      id_mysql,
      odb::alias_traits< ::country,
        id_mysql,
        access::view_traits_impl< ::employee_country_objects, id_mysql >::nat_tag> >
    nat;
  };

  // employer_with_employees
  //
  struct access::view_traits_impl< ::employer_with_employees, id_mysql >::query_columns
  {
    // employer
    //
    typedef
    odb::pointer_query_columns<
      ::employer,
      id_mysql,
      odb::access::object_traits_impl< ::employer, id_mysql > >
    employer;

    // employee
    //
    typedef
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
    employee;
  };

  // employee_vacation2
  //
  struct access::view_traits_impl< ::employee_vacation2, id_mysql >::query_columns:
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
  {
  };

  // employee_prev_employer
  //
  struct access::view_traits_impl< ::employee_prev_employer, id_mysql >::query_columns
  {
    // employee
    //
    typedef
    odb::pointer_query_columns<
      ::employee,
      id_mysql,
      odb::access::object_traits_impl< ::employee, id_mysql > >
    employee;

    // employer
    //
    typedef
    odb::pointer_query_columns<
      ::employer,
      id_mysql,
      odb::access::object_traits_impl< ::employer, id_mysql > >
    employer;
  };
}

#include "employee-odb.ixx"

#include <odb/post.hxx>

#endif // EMPLOYEE_ODB_HXX
