/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `employee`;

DROP TABLE IF EXISTS `employer`;

DROP TABLE IF EXISTS `country`;

CREATE TABLE `country` (
  `code` VARCHAR(255) NOT NULL PRIMARY KEY,
  `name` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `employer` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `name` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `employee` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `first` TEXT NOT NULL,
  `last` TEXT NOT NULL,
  `age` SMALLINT UNSIGNED NOT NULL,
  `residence` VARCHAR(255) NULL,
  `nationality` VARCHAR(255) NULL,
  `employed_by` BIGINT UNSIGNED NULL
  /*
  CONSTRAINT `employee_residence_fk`
    FOREIGN KEY (`residence`)
    REFERENCES `country` (`code`)
  */
  /*
  CONSTRAINT `employee_nationality_fk`
    FOREIGN KEY (`nationality`)
    REFERENCES `country` (`code`)
  */
  /*
  CONSTRAINT `employee_employed_by_fk`
    FOREIGN KEY (`employed_by`)
    REFERENCES `employer` (`id`)
  */)
 ENGINE=InnoDB;

